#!/usr/bin/env python3
"""Package the native project and offline basemap generator, excluding ignored caches."""
import pathlib
import subprocess
import zipfile

root = pathlib.Path(__file__).resolve().parents[1]
paths = subprocess.check_output(
    ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "testingReplic"],
    cwd=root,
).decode().split("\0")
paths += ["tools/fetch_gaza_basemap.py", "tools/package_unity_source.py"]
paths += ["tools/prepare_equipment_audio.py"]
paths += [str(path.relative_to(root)) for path in
          (root / "attached_assets/generated_audio").glob("new-gaza-*.mp3")]
destination = root / "exports/NewGaza-Unity-Source.zip"
destination.parent.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
    for name in sorted(set(filter(None, paths))):
        path = root / name
        if path.is_file():
            archive.write(path, name)
with zipfile.ZipFile(destination) as archive:
    error = archive.testzip()
    if error:
        raise RuntimeError("Archive CRC failed: " + error)
    names = set(archive.namelist())
    required = {
        "testingReplic/Assets/NewGaza/Resources/GazaBasemap.json",
        "testingReplic/MapData/GazaBasemap-source.json.gz",
        "testingReplic/Assets/NewGaza/Resources/NewGazaSea.shader",
        "testingReplic/Assets/NewGaza/Runtime/CityAudio.cs",
        "testingReplic/Assets/NewGaza/World/EquipmentTrackRig.cs",
        "testingReplic/Assets/NewGaza/UI/CityHudAudio.cs",
    }
    required.update("testingReplic/Assets/NewGaza/Resources/Audio/" + key + ".wav" for key in
        ("excavator_engine", "truck_engine", "dozer_engine", "hydraulics", "tracks",
         "wind_high", "coastal_surf", "ui_click", "ui_confirm"))
    if not required <= names:
        raise RuntimeError("Missing native city resources: " + str(required - names))
    if any("/cache/" in name or "/bin/" in name or "/obj/" in name for name in names):
        raise RuntimeError("Generated caches must not be packaged")
    if any(name.startswith("testingReplic/Assets/NewGaza/") and name.endswith(".meta")
           for name in names):
        raise RuntimeError("NewGaza .meta files must be generated by the user's Unity editor")
print(f"{destination.relative_to(root)}: {destination.stat().st_size:,} bytes; {len(names)} files; CRC OK")